#spring:
#  data:
#    redis:
#      host: 192.168.20.130
#      port: 6379
#      password: 733806_Mmy
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 0
#          max-wait: 100ms
